"use client";
import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/Transition";
import PreloadingScreen from "@/components/PreloadingScreen";

const inter = PT_Serif({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <PreloadingScreen />
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
